name: run main.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
      gemini_api_key: ${{ secrets.gemini_api_key }}

    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install "beautifulsoup4==4.9.1"
          python -m pip install "dateparser==0.7.6"
          python -m pip install "requests==2.24.0"
          python -m pip install "feedparser==6.0.8"
          python -m pip install --no-deps pygooglenews
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python main.py


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
